### ISSUE TITLE
Customer can't run this when using AWS

### ISSUE THREAD

**Issue by vperezjimenez** [newrelic-experimental/tls-proxy#5]
## Description
My customer is having trouble when using this solution in their AWS-hosted applications:

## Steps to Reproduce

From the customer:

> we created a container with squid inside and deployed it on our konvoy cluster
> the configuration is identical to the one present in the project you are indicating both as regards the proxy container and as regards the instrumented application.
> The container is properly up and running, if I try to access its endpoint via url, I find the call in the access.log

Output:

`023-10-25T09:18:05,133+0200 [16811 31] com.newrelic.agent.rpm.RPMConnectionServiceImpl INFO: Failed to connect to collector.eu01.nr-data.net:443 for ns-generico: com.newrelic.agent.transport.HttpError: collector.eu01.nr-data.net received a bad request format (400)`

## Expected Behavior

We expected this to work without further configuration.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

Java 5 application running on a Konvoy Cluster. AWS ALB involved.

**Comment by dpacheconr** [comment]
added EU and US as allowed domains in the proxy
